//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/openstack-k8s-operators/lib-common/modules/common/condition"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsoleSpec) DeepCopyInto(out *ConsoleSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsoleSpec.
func (in *ConsoleSpec) DeepCopy() *ConsoleSpec {
	if in == nil {
		return nil
	}
	out := new(ConsoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseSpec) DeepCopyInto(out *DatabaseSpec) {
	*out = *in
	out.Size = in.Size.DeepCopy()
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseSpec.
func (in *DatabaseSpec) DeepCopy() *DatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataverseExporter) DeepCopyInto(out *DataverseExporter) {
	*out = *in
	if in.Feedback != nil {
		in, out := &in.Feedback, &out.Feedback
		*out = new(DataverseExporterFeedback)
		(*in).DeepCopyInto(*out)
	}
	if in.Transcripts != nil {
		in, out := &in.Transcripts, &out.Transcripts
		*out = new(DataverseExporterTranscripts)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataverseExporter.
func (in *DataverseExporter) DeepCopy() *DataverseExporter {
	if in == nil {
		return nil
	}
	out := new(DataverseExporter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataverseExporterFeedback) DeepCopyInto(out *DataverseExporterFeedback) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataverseExporterFeedback.
func (in *DataverseExporterFeedback) DeepCopy() *DataverseExporterFeedback {
	if in == nil {
		return nil
	}
	out := new(DataverseExporterFeedback)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataverseExporterTranscripts) DeepCopyInto(out *DataverseExporterTranscripts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataverseExporterTranscripts.
func (in *DataverseExporterTranscripts) DeepCopy() *DataverseExporterTranscripts {
	if in == nil {
		return nil
	}
	out := new(DataverseExporterTranscripts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevSpec) DeepCopyInto(out *DevSpec) {
	*out = *in
	if in.FeatureFlags != nil {
		in, out := &in.FeatureFlags, &out.FeatureFlags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OKPRagOnly != nil {
		in, out := &in.OKPRagOnly, &out.OKPRagOnly
		*out = new(bool)
		**out = **in
	}
	if in.RhosMCP != nil {
		in, out := &in.RhosMCP, &out.RhosMCP
		*out = new(RhosMCPSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevSpec.
func (in *DevSpec) DeepCopy() *DevSpec {
	if in == nil {
		return nil
	}
	out := new(DevSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LCoreSpec) DeepCopyInto(out *LCoreSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LCoreSpec.
func (in *LCoreSpec) DeepCopy() *LCoreSpec {
	if in == nil {
		return nil
	}
	out := new(LCoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OGXSpec) DeepCopyInto(out *OGXSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OGXSpec.
func (in *OGXSpec) DeepCopy() *OGXSpec {
	if in == nil {
		return nil
	}
	out := new(OGXSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OKPSpec) DeepCopyInto(out *OKPSpec) {
	*out = *in
	if in.Offline != nil {
		in, out := &in.Offline, &out.Offline
		*out = new(bool)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OKPSpec.
func (in *OKPSpec) DeepCopy() *OKPSpec {
	if in == nil {
		return nil
	}
	out := new(OKPSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackLightspeed) DeepCopyInto(out *OpenStackLightspeed) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackLightspeed.
func (in *OpenStackLightspeed) DeepCopy() *OpenStackLightspeed {
	if in == nil {
		return nil
	}
	out := new(OpenStackLightspeed)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenStackLightspeed) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackLightspeedConfigSpec) DeepCopyInto(out *OpenStackLightspeedConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackLightspeedConfigSpec.
func (in *OpenStackLightspeedConfigSpec) DeepCopy() *OpenStackLightspeedConfigSpec {
	if in == nil {
		return nil
	}
	out := new(OpenStackLightspeedConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackLightspeedCore) DeepCopyInto(out *OpenStackLightspeedCore) {
	*out = *in
	out.Lightspeed = in.Lightspeed
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make([]OpenStackLightspeedModelSpec, len(*in))
		copy(*out, *in)
	}
	if in.DataverseExporter != nil {
		in, out := &in.DataverseExporter, &out.DataverseExporter
		*out = new(DataverseExporter)
		(*in).DeepCopyInto(*out)
	}
	if in.OGX != nil {
		in, out := &in.OGX, &out.OGX
		*out = new(OGXSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.LCore != nil {
		in, out := &in.LCore, &out.LCore
		*out = new(LCoreSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RAG != nil {
		in, out := &in.RAG, &out.RAG
		*out = new(RAG)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackLightspeedCore.
func (in *OpenStackLightspeedCore) DeepCopy() *OpenStackLightspeedCore {
	if in == nil {
		return nil
	}
	out := new(OpenStackLightspeedCore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackLightspeedDefaults) DeepCopyInto(out *OpenStackLightspeedDefaults) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackLightspeedDefaults.
func (in *OpenStackLightspeedDefaults) DeepCopy() *OpenStackLightspeedDefaults {
	if in == nil {
		return nil
	}
	out := new(OpenStackLightspeedDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackLightspeedList) DeepCopyInto(out *OpenStackLightspeedList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenStackLightspeed, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackLightspeedList.
func (in *OpenStackLightspeedList) DeepCopy() *OpenStackLightspeedList {
	if in == nil {
		return nil
	}
	out := new(OpenStackLightspeedList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenStackLightspeedList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackLightspeedModelSpec) DeepCopyInto(out *OpenStackLightspeedModelSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackLightspeedModelSpec.
func (in *OpenStackLightspeedModelSpec) DeepCopy() *OpenStackLightspeedModelSpec {
	if in == nil {
		return nil
	}
	out := new(OpenStackLightspeedModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackLightspeedSpec) DeepCopyInto(out *OpenStackLightspeedSpec) {
	*out = *in
	in.OpenStackLightspeedCore.DeepCopyInto(&out.OpenStackLightspeedCore)
	if in.Database != nil {
		in, out := &in.Database, &out.Database
		*out = new(DatabaseSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.OKP != nil {
		in, out := &in.OKP, &out.OKP
		*out = new(OKPSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Quotas != nil {
		in, out := &in.Quotas, &out.Quotas
		*out = new(QuotaSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Dev.DeepCopyInto(&out.Dev)
	if in.Console != nil {
		in, out := &in.Console, &out.Console
		*out = new(ConsoleSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackLightspeedSpec.
func (in *OpenStackLightspeedSpec) DeepCopy() *OpenStackLightspeedSpec {
	if in == nil {
		return nil
	}
	out := new(OpenStackLightspeedSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenStackLightspeedStatus) DeepCopyInto(out *OpenStackLightspeedStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(condition.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenStackLightspeedStatus.
func (in *OpenStackLightspeedStatus) DeepCopy() *OpenStackLightspeedStatus {
	if in == nil {
		return nil
	}
	out := new(OpenStackLightspeedStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaLimiterSpec) DeepCopyInto(out *QuotaLimiterSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaLimiterSpec.
func (in *QuotaLimiterSpec) DeepCopy() *QuotaLimiterSpec {
	if in == nil {
		return nil
	}
	out := new(QuotaLimiterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaSchedulerSpec) DeepCopyInto(out *QuotaSchedulerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaSchedulerSpec.
func (in *QuotaSchedulerSpec) DeepCopy() *QuotaSchedulerSpec {
	if in == nil {
		return nil
	}
	out := new(QuotaSchedulerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaSpec) DeepCopyInto(out *QuotaSpec) {
	*out = *in
	if in.Limiters != nil {
		in, out := &in.Limiters, &out.Limiters
		*out = make([]QuotaLimiterSpec, len(*in))
		copy(*out, *in)
	}
	if in.Scheduler != nil {
		in, out := &in.Scheduler, &out.Scheduler
		*out = new(QuotaSchedulerSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaSpec.
func (in *QuotaSpec) DeepCopy() *QuotaSpec {
	if in == nil {
		return nil
	}
	out := new(QuotaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RAG) DeepCopyInto(out *RAG) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RAG.
func (in *RAG) DeepCopy() *RAG {
	if in == nil {
		return nil
	}
	out := new(RAG)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RhosMCPSpec) DeepCopyInto(out *RhosMCPSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RhosMCPSpec.
func (in *RhosMCPSpec) DeepCopy() *RhosMCPSpec {
	if in == nil {
		return nil
	}
	out := new(RhosMCPSpec)
	in.DeepCopyInto(out)
	return out
}
